INSERT INTO `topuv`.`uv` (`id`, `label`, `id_description`, `avg_mark`, `id_category`) VALUES 
("CHMA01", "Structure et transformation de la matière", "", "", "1"),
("CHMA02", "Chimie des procédés industriels", "", "", "1"),
("CHMA03", "Structure et propriétés des solides", "", "", "1"),
("CHMA04", "Analyse chimique, sûreté et environnement", "", "", "1"),
("EA01", "Automatique et asservissement", "", "", "1"),
("EA03", "Actionneurs", "", "", "1"),
("FQ03", "Plans d’expériences", "", "", "1"),
("FQ04", "Sûreté de fonctionnement : méthodes et outils de base", "", "", "1"),
("GP27", "Méthodes de prévision des demandes et de gestion des stocks", "", "", "1"),
("GS13", "Gestion de la sécurité", "", "", "1"),
("GS15", "Cryptologie et signature électronique", "", "", "1"),
("IF01", "Théorie et codage de l’information", "", "", "1"),
("IF02", "Modélisation pour la conception des Systèmes d’Information", "", "", "1"),
("IF05", "Qualité du logiciel", "", "", "1"),
("IF10", "Design centre usage de logiciels et de services", "", "", "1"),
("IF15", "Ingénierie des connaissances", "", "", "1"),
("IF19", "Sociologie des organisations pour l'ingénieur en système d'information", "", "", "1"),
("IF23", "Géo-localisation", "", "", "1"),
("IF25", "Identité numérique, e-réputation et réseaux sociaux", "", "", "1"),
("LO01", "Bases de l’informatique", "", "", "1"),
("LO12", "Intelligence artificielle et applications", "", "", "1"),
("LO13", "Infographie 3D : théorie et applications", "", "", "1"),
("MA02", "Physique de la matière", "", "", "1"),
("MA03", "Interaction Rayonnement-Matière", "", "", "1"),
("MA04", "Chimie pour les matériaux", "", "", "1"),
("MA11", "Matériaux métalliques", "", "", "1"),
("MA12", "Matériaux non métalliques", "", "", "1"),
("MA13", "Mécanique des matériaux", "", "", "1"),
("MA14", "Semi-conducteurs et matériaux pour les technologies avancées", "", "", "1"),
("MATH01", "Bases mathématiques pour l'ingénieur", "", "", "1"),
("MATH02", "Outils mathématiques pour l’ingénieur", "", "", "1"),
("MATH03", "Algèbre linéaire", "", "", "1"),
("MATH04", "Analyse avancée", "", "", "1"),
("MQ01", "Éléments de résistance des matériaux", "", "", "1"),
("MQ02", "Initiation à la mécanique des milieux continus solides", "", "", "1"),
("MQ03", "Études dynamique et vibratoire de systèmes mécaniques", "", "", "1"),
("MQ04", "Propriétés des matériaux", "", "", "1"),
("MQ07", "Mécanique des fluides", "", "", "1"),
("MQ13", "Thermodynamique et thermique des machines", "", "", "1"),
("MT12", "Techniques mathématiques de l’ingénieur", "", "", "1"),
("MT13", "Méthodes numériques pour l’ingénieur", "", "", "1"),
("MT14", "Recherche opérationnelle", "", "", "1"),
("NF16", "Bases de données", "", "", "1"),
("NF20", "Modélisation et évaluation des systèmes complexes", "", "", "1"),
("NM01", "Nanomatériaux et nanotechnologies", "", "", "1"),
("OP01", "Matériaux pour l’optique et l’optoélectronique", "", "", "1"),
("PHYS01", "Bases de physique pour l'ingénieur", "", "", "1"),
("PHYS02", "Mécanique", "", "", "1"),
("PHYS03", "Champs, ondes, vibrations, propagation", "", "", "1"),
("PHYS04", "Thermique, énergétique et machines thermodynamiques", "", "", "1"),
("PHYS05", "Conversion, transport et transformation d'énergie", "", "", "1"),
("RE02", "Transmission de l’information", "", "", "1"),
("RE04", "Télécommunications d’entreprise", "", "", "1"),
("RE15", "Réseaux à qualité de services ", "", "", "1"),
("RE23", "Gestion et contrôle des réseaux", "", "", "1"),
("SM06", "Modélisation des phénomènes thermomécaniques couplés", "", "", "1"),
("SY01", "Eléments de probabilités", "", "", "1"),
("SY02", "Statistiques pour l’ingénieur", "", "", "1"),
("SY04", "Outils pour la modélisation des réseaux", "", "", "1"),
("SY05", "Outils d’aide à la décision", "", "", "1"),
("SY06", "Analyse et traitement du signal", "", "", "1"),
("SY08", "Traitement de signal multimédia", "", "", "1"),
("SY12", "Eléments d’automatisme et contrôle industriel", "", "", "1"),
("SY13", "Régulation automatique", "", "", "1"),
("SY14", "Systémique et dynamique des systèmes", "", "", "1"),
("SY16", "Traitement numérique du signal et des images", "", "", "1"),
("SY18", "Outils de modélisation et d’évaluation des performances", "", "", "1"),
("SY24", "Traitement de l'information et sécurité", "", "", "1"),




("CL01", "Echanges internationaux et commerce international", "", "", "2"),
("CL02", "Conditionnement, manutention et entreposage", "", "", "2"),
("CL03", "Logistique de transport et de distribution", "", "", "2"),
("CL04", "Coordination des relations clients-fournisseurs", "", "", "2"),
("CL07", "Soutien logistique intégré et service après-vente", "", "", "2"),
("CS01", "Analyse de la valeur - Analyse fonctionnelle", "", "", "2"),
("CS02", "Conception de systèmes mécaniques complexes", "", "", "2"),
("CS03", "Conduite de projets", "", "", "2"),
("CS05", "Flux de matière et économie des matériaux", "", "", "2"),
("DI02", "Méthodes de diagnostic des systèmes industriels", "", "", "2"),
("DS01", "Design et sensorique", "", "", "2"),
("EA02", "Mise en œuvre de systèmes automatiques", "", "", "2"),
("EA04", "Capteurs et mesure", "", "", "2"),
("EG01", "Ergonomie des postes de travail", "", "", "2"),
("EG23", "Interface Homme-Machine et ergonomie", "", "", "2"),
("EN01", "Eléments de base en électronique", "", "", "2"),
("EN03", "Systèmes électroniques", "", "", "2"),
("EV10", "Analyse environnementale : méthodes et outils de base", "", "", "2"),
("EV11", "Management du cycle de vie des matériaux", "", "", "2"),
("EV12", "Eco-conception, technologies propres et recyclage", "", "", "2"),
("CFQ01", "Assurance et contrôle de la qualité", "", "", "2"),
("FQ02", "Techniques et méthodes de maintenance", "", "", "2"),
("FQ05", "Sûreté de fonctionnement et retour d’expérience", "", "", "2"),
("GE40", "Commerce des matériaux", "", "", "2"),
("GP06", "Organisation et gestion de la production", "", "", "2"),
("GP17", "Planification et ordonnancement de la production", "", "", "2"),
("GP28", "Excellence Industrielle", "", "", "2"),
("GS11", "Techniques de sécurité pour l'entreprise", "", "", "2"),
("IF03", "Initiation à la Sécurité des Systèmes d'Information", "", "", "2"),
("IF04", "et stratégie industrielle", "", "", "2"),
("IF08", "Management de projets informatiques", "", "", "2"),
("IF09", "Systèmes documentaires", "", "", "2"),
("IF11", "EDI et commerce électronique", "", "", "2"),
("IF14", "Analyse du système d’information", "", "", "2"),
("IF16", "Groupware et Workflow : concepts et mise en œuvre", "", "", "2"),
("IF17", "Architectures décisionnelles", "", "", "2"),
("IF20", "Gestion intégrée et modélisation des processus", "", "", "2"),
("IF22", "Gestion des Systèmes d’Information", "", "", "2"),
("IF24", "Progiciels de gestion intégrée, SAP", "", "", "2"),
("IF26", "Conception sécurisée d'applications : Web Mobile et Smartphones", "", "", "2"),
("IF27", "Sécurisation de services", "", "", "2"),
("LO02", "Principe et pratique de la programmation objets", "", "", "2"),
("LO07", "Technologies du web", "", "", "2"),
("LO10", "Design patterns pour systèmes orientés services", "", "", "2"),
("LO11", "Architectures programmables ", "", "", "2"),
("LO14", "Administration des systèmes", "", "", "2"),
("LO15", "PLM et ingénierie collaborative", "", "", "2"),
("MA15", "Technologie des matériaux non métalliques", "", "", "2"),
("MA20", "Analyses et caractérisations microscopiques des matériaux", "", "", "2"),
("MA21", "Analyses et caractérisations macroscopiques des matériaux", "", "", "2"),
("MM01", "Multimédia, du projet à la réalisation", "", "", "2"),
("MQ06", "Modélisation des structures par éléments finis", "", "", "2"),
("MQ08", "Analyse théorique et expérimentale des contraintes", "", "", "2"),
("MQ09", "Maillage et méthodes d’adaptation", "", "", "2"),
("MQ10", "Simulation numérique des procédés mécaniques", "", "", "2"),
("MQ12", "Mise en forme des matériaux et des structures", "", "", "2"),
("MS11", "Mesure physique et instrumentation", "", "", "2"),
("NF02", "Technologie générale des systèmes informatiques", "", "", "2"),
("NF04", "Algorithmique", "", "", "2"),
("NF05", "Introduction au langage C", "", "", "2"),
("NF15", "Systèmes avancés d’aide à la conception", "", "", "2"),
("NF18", "Intéropérabilité PLM, Architectures orientées Service et Virtualisation", "", "", "2"),
("NF19", "et des bases de données", "", "", "2"),
("NR01", "Normes et réglementations", "", "", "2"),
("OB01", "Outils scientifiques de base pour l’ingénieur", "", "", "2"),
("PR01", "Procédés et matériaux métalliques", "", "", "2"),
("RE01", "Réseaux d’entreprise", "", "", "2"),
("RE06", "Téléphonie d’entreprise", "", "", "2"),
("RE12", "Services Réseaux", "", "", "2"),
("RE13", "Réseaux mobiles et sans fil", "", "", "2"),
("RE16", "Sécurisation des réseaux", "", "", "2"),
("RE20", "Réseaux d’opérateurs", "", "", "2"),
("RE21", "Usages, services et ergonomie des terminaux", "", "", "2"),
("SM02", "Modélisation avancée des structures par éléments finis", "", "", "2"),
("SY15", "Simulation des systèmes industriels", "", "", "2"),
("SY17", "Conception préliminaire des systèmes de production", "", "", "2"),
("SY20", "Intelligence Industrielle", "", "", "2"),
("SY22", "Systèmes sans fil", "", "", "2"),
("SY23", "Systèmes embarqués", "", "", "2"),
("SY25", "Réseaux de capteurs", "", "", "2"),
("TITS", "Travail d’Investigation Technologique et Scientifique", "", "", "2"),
("TN01", "Initiation à la définition et à la fabrication d’un objet technique", "", "", "2"),
("TN02", "Technologie et initiation au bureau d’études", "", "", "2"),
("TN04", "Gestion et réalisation d'un projet d'ingénierie : initiation", "", "", "2"),
("TN08", "Initiation à la mise en œuvre de la matière", "", "", "2"),
("TN12", "Eléments de bureau d’études", "", "", "2"),
("TN14", "Initiation à la CAO : modélisation géométrique", "", "", "2"),
("TN15", "Techniques de fabrication conventionnelles", "", "", "2"),
("TN16", "Ingénierie numérique et administration CFAO", "", "", "2"),
("TN17", "Technologie de fabrication et outils méthodes", "", "", "2"),
("TN18", "Techniques de fabrication avancées", "", "", "2"),
("TN19", "Techniques d’achat et de réduction des coûts", "", "", "2"),
("TN20", "Étude et dimensionnement de systèmes mécaniques", "", "", "2"),
("TN4B", "Gestion et réalisation d'un projet d'ingénierie : approfondissement", "", "", "2"),
("TS01", "Sécurité des systèmes", "", "", "2"),
("TS02", "Gestion des risques industriels", "", "", "2"),





("AM01", "Activité musicale", "", "", "3"),
("AP01", "Peindre, écrire ou dessiner", "", "", "3"),
("AP02", "Objets trouvés / objets réinventés", "", "", "3"),
("AP03", "Image, imaginaire et nouvelles technologies", "", "", "3"),
("AT01", "Activité Théâtre", "", "", "3"),
("EE06", "L’entreprise dans le contexte européen et international", "", "", "3"),
("EP01", "Ethique et performance dans l’entreprise", "", "", "3"),
("EV00", "Philosophie de l’environnement", "", "", "3"),
("EV01", "Bases scientifiques de l’environnement", "", "", "3"),
("EV02", "Economie de l’environnement", "", "", "3"),
("EV03", "Droit de l’environnement", "", "", "3"),
("EV04", "Risques environnementaux : gestion et controverses", "", "", "3"),
("HT03", "Regards sur l’histoire de l’art", "", "", "3"),
("HT05", "Histoire de la physique et de l’astronomie", "", "", "3"),
("HT06", "Histoire contemporaine et industrialisation", "", "", "3"),
("HT07", "Géopolitique du monde contemporain", "", "", "3"),
("HT08", "Initiation à l’archéologie", "", "", "3"),
("IC01", "La diversité interculturelle : la France en perspective", "", "", "3"),
("LI01", "Atelier d’écriture", "", "", "3"),
("LI03", "L’art du récit", "", "", "3"),
("LI04", "Littérature, culture et société", "", "", "3"),
("PH15", "Essor des technologies et crise de l’idée de progrès", "", "", "3"),
("PH16", "Langage et politique : introduction à la philosophie politique", "", "", "3"),
("PH19", "La nature de l'Homme", "", "", "1"),
("PO03", "Introduction à la vie politique", "", "", "3"),
("SC00", "Approches de la communication", "", "", "3"),
("SC01", "Communication d’entreprise", "", "", "3"),
("SC02", "Communication et médias", "", "", "3"),
("SC04", "Psychologie et communication", "", "", "3"),
("SC05", "Psychologie cognitive et psychologie du travail", "", "", "3"),
("SC06", "Usage des technologies de la communication et innovation", "", "", "3"),
("SE01", "Histoire des idées économiques", "", "", "3"),
("SE02", "Economie générale pour l’ingénieur", "", "", "3"),
("SO02", "sociétaux et géopolitique des conflits", "", "", "3"),
("SO03", "Evènementiel et sociétés démocratiques", "", "", "3"),
("SO04", "Sécurité, Etat et responsabilité", "", "", "3"),
("SO05", "Gestion des systèmes sociotechniques à risque", "", "", "3"),
("SO08", "Se préparer au monde du travail avec les sciences sociales", "", "", "3"),
("SP01", "Initiation à l’animation sportive", "", "", "3"),
("SP02", "Animateur sportif", "", "", "3"),
("SP03", "Animateur qualifié", "", "", "3"),
("SP11", "Projet de performance sportive", "", "", "3"),
("SP20", "Conception d’un évènement sportif", "", "", "3"),





("GE04", "Gestion des ressources humaines", "", "", "4"),
("GE10", "Introduction à la microéconomie", "", "", "4"),
("GE11", "Organisation et décision", "", "", "4"),
("GE21", "L’entreprise et le droit", "", "", "4"),
("GE25", "Propriété intellectuelle et intelligence économique", "", "", "4"),
("GE28", "Droit du commerce et des affaires", "", "", "4"),
("GE31", "L’entreprise et la gestion", "", "", "4"),
("GE32", "Ingénierie financière de l’entreprise", "", "", "4"),
("GE33", "Projet de synthèse de gestion d’entreprise", "", "", "4"),
("GE34", "Stratégie et management de l’entreprise", "", "", "4"),
("GE36", "Marketing", "", "", "4"),
("GE37", "Management de l’innovation", "", "", "4"),
("GE41", "Technologie et Management", "", "", "4"),
("GE43", "Création d’entreprise : phase pratique", "", "", "4"),
("GE44", "Approche multiculturelle du business et du management", "", "", "4"),






("FM01", "(langue maternelle) Parcours semi-autonome", "", "", "5"),
("FM02", "Maîtrise des nuances de la langue française", "", "", "5"),
("IT00", "Italien - Niveau débutant", "", "", "5"),
("IT01", "Italien - Niveau élémentaire/structures de base", "", "", "5"),
("IT02", "Italien - Niveau moyen", "", "", "5"),
("LC00", "Initiation à la langue moderne et à la culture chinoises 1", "", "", "5"),
("LC01", "Initiation à la langue moderne et à la culture chinoises 2", "", "", "5"),
("LC02", "Langue moderne et culture chinoises - niveau intermédiaire", "", "", "5"),
("LE00", "Anglais - Niveau débutant/remise à niveau", "", "", "5"),
("LE01", "Anglais - Niveau élémentaire/structures de base", "", "", "5"),
("LE02", "Anglais - Niveau moyen", "", "", "5"),
("LE03", "Anglais - Niveau pratique", "", "", "5"),
("LE08", "L’anglais pour le monde du travail", "", "", "5"),
("LE11", "Anglais pratique dans les domaines scientifiques et techniques", "", "", "5"),
("LE12", "Cultures télévisuelles nord-américaines", "", "", "5"),
("LE14", "English Skills 1", "", "", "5"),
("LE15", "English Skills 2 – Globish or English?", "", "", "5"),
("LE16", "Communication orale et cinéma", "", "", "5"),
("LE17", "English for Academic Purposes", "", "", "5"),
("LE18", "Patrimoine mondial : world heritage", "", "", "5"),
("LF00", "Français langue étrangère", "", "", "5"),
("LF05", "Français - soutien linguistique", "", "", "5"),
("LF10", "Français langue étrangère - niveau faux débutant 1", "", "", "5"),
("LF11", "Français langue étrangère - niveau faux débutant 2", "", "", "5"),
("LF14", "Français langue étrangère - niveau intermédiaire", "", "", "5"),
("LF15", "Français langue étrangère - techniques d’écriture", "", "", "5"),
("LF20", "Français pratique pour le cours de mathématiques", "", "", "5"),
("LF21", "Français pratique pour le cours de chimie", "", "", "5"),
("LF22", "Français pratique pour le cours de physique", "", "", "5"),
("LF23", "Soutien phonétique en français", "", "", "5"),
("LF24", "Préparation à la soutenance", "", "", "5"),
("LF30", "Français langue étrangère - langue et culture", "", "", "5"),
("LF31", "Français langue étrangère - langue et culture", "", "", "5"),
("LF32", "Français langue étrangère - langue et culture", "", "", "5"),
("LF33", "Français langue étrangère - langue et culture", "", "", "5"),
("LF40", "Français langue étrangère -  Niveau B1", "", "", "5"),
("LF41", "Français langue étrangère - Niveau B2", "", "", "5"),
("LG00", "Allemand - Niveau débutant", "", "", "5"),
("LG01", "Allemand - Niveau élémentaire/structures de base", "", "", "5"),
("LG02", "Allemand - Niveau moyen", "", "", "5"),
("LG03", "Allemand - Niveau pratique", "", "", "5"),
("LG08", "Allemand - Préparation à l’examen niveau B2", "", "", "5"),
("LG10", "Allemand «culture et civilisation»", "", "", "5"),
("LG11", "Allemand «professionnel»", "", "", "5"),
("LP00", "lusophones 1", "", "", "5"),
("LP01", "lusophones 2", "", "", "5"),
("LP02", "niveau intermédiaire", "", "", "5"),
("LS00", "Espagnol - Niveau débutant", "", "", "5"),
("LS01", "Espagnol - Niveau élémentaire/structures de base", "", "", "5"),
("LS02", "Espagnol - Niveau moyen", "", "", "5"),
("LS03", "Espagnol - Niveau pratique", "", "", "5"),
("LS08", "Espagnol - Préparation à l’examen niveau B2", "", "", "5"),
("LS10", "Espagnol - Niveau autonome", "", "", "5"),
("LS11", "Espagnol - Niveau professionnel Espagne et Amérique latine", "", "", "5"),
("SD10", "Expression, communication et recherche documentaire", "", "", "5"),
("SI10", "Formation à la communication écrite et orale", "", "", "5"),
("SI11", "Communication écrite et orale pour l’ingénieur", "", "", "5"),





("TN05", "Stage technique", "", "", "6"),
("TN07", "Stage à l’étranger", "", "", "6"),
("TN09", "Stage professionnel", "", "", "6"),
("TN10", "Projet de fin d’études", "", "", "6"),
("TN30", "Stage Master", "", "", "6"),
("TN31", "Stage spécial en environnement et développement durable", "", "", "6"),
("TN32", "Essai en environnement et développement durable", "", "", "6"),
("TN33", "et développement durable", "", "", "6"),
("TN40", "Projet en laboratoire pour un étudiant d’échange", "", "", "6"),
("TN51", "Projet de fin d'études en alternance Partie I", "", "", "6"),
("TN52", "Projet de fin d'études en alternance Partie II", "", "", "6"),




("AC", "Acquisition de connaissances", "", "", "7"),
("AV", "Réalisation multimédia", "", "", "7"),
("EC01", "Éco-conception", "", "", "7"),
("EI01", "Ecologie industrielle", "", "", "7"),
("ER", "Enquête et recherche documentaire", "", "", "7"),
("GL01", "Introduction au génie logiciel", "", "", "7"),
("CGS10", "Sécurité des SI, problématique, aspects légaux et réglementaires", "", "", "7"),
("GS16", "Sécurité des réseaux de l'Internet", "", "", "7"),
("GS21", "Cyber-enquête en entreprise", "", "", "7"),
("GS22", "Recherche de la preuve numérique", "", "", "7"),
("IAMC01", "Composites", "", "", "7"),
("IAMC02", "Lois de comportement - Formulation et Identification", "", "", "7"),
("IR30", "Initiation à la recherche", "", "", "7"),
("IS01", "Structures du sport en France", "", "", "7"),
("IS03", "Stratégie de communication", "", "", "7"),
("IS04", "Ressources Humaines : manager une équipe dans le secteur sportif", "", "", "7"),
("IS07", "Organisation d’évènements sportifs", "", "", "7"),
("IS08", "Modélisation de la logistique événementielle", "", "", "7"),
("IS09", "Gestion des infrastructures de sport et de loisirs", "", "", "7"),
("IS11", "Sécurité événementielle", "", "", "7"),
("IS17", "Publicité marketing direct - Stratégie et technique de vente", "", "", "7"),
("ISC04", "Plateformes orientées services", "", "", "7"),
("ISC07", "Applications de services", "", "", "7"),
("ISC08", "Qualité de service et évaluation", "", "", "7"),
("MA2S", "Soutien à l'UV MA02", "", "", "7"),
("MA3S", "Bases de l'interaction rayonnement matière", "", "", "7"),
("ME01", "Evaluation environnementale", "", "", "7"),
("ME02", "Management du développement durable", "", "", "7"),
("ME05", "Eco-technologies", "", "", "7"),
("ME09", "Préparation à l’essai en environnement et développement durable", "", "", "7"),
("MI01", "Découverte des industries du Pôle Technologique de Nogent", "", "", "7"),
("MO12", "Optique de champ proche, aspect fondamental et technologique", "", "", "7"),
("MO13", "Spectroscopie optique", "", "", "7"),
("MO23", "Méthodes mathématiques et numériques en optique", "", "", "7"),
("MP01", "Gestion des ressources de l'entreprise, SAP", "", "", "7"),
("MP02", "Méthodes d'ingénierie collaborative", "", "", "7"),
("MP03", "Ingénierie des connaissances, websémantique et SI", "", "", "7"),
("MT11", "Révision d’analyse et d’algèbre", "", "", "7"),
("NT01", "Nanotechnologies et Industrie", "", "", "7"),
("OS01", "Fondement de la recherche opérationnelle", "", "", "7"),
("OS02", "Théorie de la décision et de l’estimation : approche stochastique", "", "", "7"),
("OS03", "Processus stochastiques", "", "", "7"),
("OS06", "Approche bayésienne pour les problèmes inverses", "", "", "7"),
("OS10", "et l’ordonnancement de la production", "", "", "7"),
("OS11", "Modèles et algorithmes pour la logistique et le transport", "", "", "7"),
("OS13", "Modèles pour la fiabilité et la maintenance", "", "", "7"),
("OS14", "Reconnaissance des formes et applications en surveillance", "", "", "7"),
("SG11", "cybercriminalité ", "", "", "7"),
("SG12", "Politique de sécurité et concept transversal", "", "", "7"),
("SG22", "Risques majeurs, communication de crises et économie de la sécurité", "", "", "7"),
("SG31", "Analyse des systèmes et gestion des connaissances", "", "", "7"),
("SG32", "Réseaux de systèmes informatiques et urbains ", "", "", "7"),
("SG41", "Fondamentaux de la gestion des crises", "", "", "7"),
("SL", "Suivi linguistique", "", "", "7"),
("TMA01", "Comportement des matériaux avancés", "", "", "7"),
("TMA02", "Techniques avancées de mesure expérimentale", "", "", "7"),
("TMA03", "Technologies de conception et d'élaboration", "", "", "7"),
("TMA04", "Méthodes numériques avancées", "", "", "7"),
("TMA05", "Mécanique des surfaces", "", "", "7"),
("TMA06", "Durabilité des matériaux et de structures", "", "", "7"),
("TMA07", "Matériaux avancés", "", "", "7"),
("TX", "Travail de réalisation et d’expérimentation", "", "", "7");